#index:
#    path: /
#    controller: App\Controller\DefaultController::index

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /admin/resetting

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

# //////////////////////////////////////////////////////////////////////////////////////////////// #

libprovas.curso.curso:
    resource: '@ApplicationLibProvasCursoBundle/Resources/config/routes/routes.yaml'
    prefix: /

libprovas.disciplina.disciplina:
    resource: '@ApplicationLibProvasDisciplinaBundle/Resources/config/routes/routes.yaml'
    prefix: /

libprovas.prova.prova:
    resource: '@ApplicationLibProvasProvaBundle/Resources/config/routes/routes.yaml'
    prefix: /

libprovas.professor.professor:
    resource: '@ApplicationLibProvasProfessorBundle/Resources/config/routes/routes.yaml'
    prefix: /

